CC = g++
SRCS = ./main.cpp ./View/LifeGameDisplayOnCurses.cpp ./View/ExpressionCell.cpp ./Controller/MatrixCell.cpp ./Model/Cell.cpp
LIBS = -lcurses
LDFLAGS = -Wall -O2

LifeGame:
	$(CC) $(LDFLAGS) $(LIBS) $(SRCS)
